// <auto-generated />
using System;
using FolkIdle.Server.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FolkIdle.Server.Migrations
{
    [DbContext(typeof(FolkIdleDbContext))]
    [Migration("20260716203252_DropPlayerChronoRegistry")]
    partial class DropPlayerChronoRegistry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FolkIdle.Server.Models.AccountAnalyticsLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LogId"));

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<long>("EventTypeHash")
                        .HasColumnType("bigint");

                    b.Property<long>("PayloadMetric")
                        .HasColumnType("bigint");

                    b.Property<long>("TimestampEpoch")
                        .HasColumnType("bigint");

                    b.HasKey("LogId");

                    b.HasIndex("AccountId", "TimestampEpoch")
                        .HasDatabaseName("IX_AccountAnalyticsLogs_AccountId_TimestampEpoch");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("AccountId", "TimestampEpoch"), "btree");

                    b.ToTable("AccountAnalyticsLogs");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.AccountChronoRegistry", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AccelerationTerminationEpoch")
                        .HasColumnType("bigint");

                    b.Property<double>("ActiveSpeedMultiplier")
                        .HasColumnType("double precision");

                    b.Property<int>("BankedChronoSeconds")
                        .HasColumnType("integer");

                    b.Property<long>("LastClockSyncEpoch")
                        .HasColumnType("bigint");

                    b.HasKey("AccountId");

                    b.ToTable("account_chrono_registry", null, t =>
                        {
                            t.HasCheckConstraint("CK_account_chrono_registry_ActiveSpeedMultiplier", "\"ActiveSpeedMultiplier\" IN (1.0, 2.0, 4.0)");

                            t.HasCheckConstraint("CK_account_chrono_registry_BankedChronoSeconds", "\"BankedChronoSeconds\" >= 0 AND \"BankedChronoSeconds\" <= 604800");
                        });
                });

            modelBuilder.Entity("FolkIdle.Server.Models.AccountSecurityQuota", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPermanentlyBlacklisted")
                        .HasColumnType("boolean");

                    b.Property<long>("LastInfractionEpoch")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalFloodInfractionsCount")
                        .HasColumnType("integer");

                    b.HasKey("AccountId");

                    b.HasIndex("AccountId", "IsPermanentlyBlacklisted")
                        .HasDatabaseName("IX_AccountSecurityQuotas_SecurityIndex");

                    b.HasIndex("IsPermanentlyBlacklisted", "LastInfractionEpoch")
                        .HasDatabaseName("IX_AccountSecurityQuotas_Blacklist_LastInfraction");

                    b.ToTable("AccountSecurityQuotas", null, t =>
                        {
                            t.HasCheckConstraint("CK_AccountSecurityQuotas_TotalFloodInfractionsCount", "\"TotalFloodInfractionsCount\" >= 0");
                        });
                });

            modelBuilder.Entity("FolkIdle.Server.Models.BankEquipmentInstance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AffixPayload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("BaseItemId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsAffixLocked")
                        .HasColumnType("boolean");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("QualityTier")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("BankEquipmentInstances");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.CharacterLineageRegistry", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<int>("GenerationIndex")
                        .HasColumnType("integer");

                    b.Property<long>("GeneticVector")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsEpicMutation")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInbred")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ParentMaternalId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentPaternalId")
                        .HasColumnType("uuid");

                    b.HasKey("CharacterId");

                    b.ToTable("character_lineage_registry");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.CharacterRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AgePhase")
                        .HasColumnType("integer");

                    b.Property<long>("AgeTicks")
                        .HasColumnType("bigint");

                    b.Property<long>("BreedingCooldownEndEpoch")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsBreedingActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLockedInEscrow")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("characters");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.CommodityRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("CommodityRecords");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.DailyQuestRecord", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("QuestSlot")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentProgress")
                        .HasColumnType("integer");

                    b.Property<long>("DateKeyUtc")
                        .HasColumnType("bigint");

                    b.Property<int>("QuestType")
                        .HasColumnType("integer");

                    b.Property<bool>("RewardClaimed")
                        .HasColumnType("boolean");

                    b.Property<int>("TargetAmount")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId", "QuestSlot");

                    b.ToTable("DailyQuestRecords");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.EcoTelemetryLedger", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LogId"));

                    b.Property<double>("CalculatedRatio")
                        .HasColumnType("double precision");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalDiamondsConsumed")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalDiamondsMinted")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalGoldConsumed")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalGoldMinted")
                        .HasColumnType("bigint");

                    b.HasKey("LogId");

                    b.ToTable("EcoTelemetryLedgers");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.EquipmentAffixMatrix", b =>
                {
                    b.Property<int>("AffixId")
                        .HasColumnType("integer");

                    b.Property<double>("GeometricalScalingFactor")
                        .HasColumnType("double precision");

                    b.Property<int>("MaxBaseValue")
                        .HasColumnType("integer");

                    b.Property<int>("MinBaseValue")
                        .HasColumnType("integer");

                    b.Property<byte>("StatType")
                        .HasColumnType("smallint");

                    b.HasKey("AffixId");

                    b.ToTable("EquipmentAffixMatrices");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.EquipmentInstance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AffixPayload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("BaseItemId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsAffixLocked")
                        .HasColumnType("boolean");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("QualityTier")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("EquipmentInstances");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.EventHorizonPremiumLedger", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("NewBalance")
                        .HasColumnType("integer");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("PreviousBalance")
                        .HasColumnType("integer");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("EventHorizonPremiumLedgers");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.GuildContributionLedger", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<long>("LifetimeContributed")
                        .HasColumnType("bigint");

                    b.HasKey("PlayerId", "GuildId", "MaterialId");

                    b.ToTable("GuildContributionLedgers");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.GuildDefenseRoster", b =>
                {
                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("GuildId"));

                    b.Property<string>("DefensiveStatsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("RegionShardId")
                        .HasColumnType("integer");

                    b.HasKey("GuildId");

                    b.HasIndex("RegionShardId", "GuildId");

                    b.ToTable("GuildDefenseRosters");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.GuildDepotBalance", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("ItemDefinitionId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("GuildId", "ItemDefinitionId");

                    b.ToTable("GuildDepotBalances");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.GuildLogisticsDepot", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<long>("CurrentStock")
                        .HasColumnType("bigint");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<long>("TargetRequirement")
                        .HasColumnType("bigint");

                    b.HasKey("GuildId", "MaterialId");

                    b.ToTable("GuildLogisticsDepots");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.GuildMatchmakingSnapshot", b =>
                {
                    b.Property<Guid>("MatchUuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActiveMatchMmr")
                        .HasColumnType("integer");

                    b.Property<long>("AttackerGuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("DefenderGuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("FencingToken")
                        .HasColumnType("bigint");

                    b.Property<long>("GlobalNodeMaxHp")
                        .HasColumnType("bigint");

                    b.Property<long>("GlobalNodeRemainingHp")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean");

                    b.Property<int>("TournamentGroupIndex")
                        .HasColumnType("integer");

                    b.HasKey("MatchUuid");

                    b.HasIndex("TournamentGroupIndex");

                    b.HasIndex("AttackerGuildId", "DefenderGuildId");

                    b.HasIndex("TournamentGroupIndex", "ActiveMatchMmr");

                    b.ToTable("GuildMatchmakingSnapshots");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.GuildMaterialSinkLedger", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CommodityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalAmountContributed")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("GuildMaterialSinkLedgers");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.GuildMember", b =>
                {
                    b.Property<long>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PlayerId"));

                    b.Property<long>("ContributionPoints")
                        .HasColumnType("bigint");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId");

                    b.HasIndex("GuildId");

                    b.ToTable("GuildMembers");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.GuildRaidState", b =>
                {
                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("GuildId"));

                    b.Property<long>("RaidBossCurrentHp")
                        .HasColumnType("bigint");

                    b.Property<long>("RaidBossMaxHp")
                        .HasColumnType("bigint");

                    b.Property<int>("RaidTier")
                        .HasColumnType("integer");

                    b.HasKey("GuildId");

                    b.ToTable("GuildRaidStates");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.GuildRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ActiveMembers")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentTier")
                        .HasColumnType("integer");

                    b.Property<int>("GuildMMR")
                        .HasColumnType("integer");

                    b.Property<int>("MaxMembers")
                        .HasColumnType("integer");

                    b.Property<int>("MiningMonolithLevel")
                        .HasColumnType("integer");

                    b.Property<int>("MiningMonolithProgress")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("TotalGoldContributed")
                        .HasColumnType("bigint");

                    b.Property<int>("WoodcuttingMonolithLevel")
                        .HasColumnType("integer");

                    b.Property<int>("WoodcuttingMonolithProgress")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("GuildRecords");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.GuildTradeListing", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MarketEquipmentInstanceId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MarketOrderRecordId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MarketEquipmentInstanceId");

                    b.HasIndex("MarketOrderRecordId");

                    b.ToTable("GuildTradeListings");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.GuildWarActiveMatch", b =>
                {
                    b.Property<long>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MatchId"));

                    b.Property<long>("AttackingGuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("CurrentStateBitmask")
                        .HasColumnType("bigint");

                    b.Property<long>("DefendingGuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("InitialSeed")
                        .HasColumnType("integer");

                    b.HasKey("MatchId");

                    b.ToTable("GuildWarActiveMatches");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.GuildWarCombatHistory", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LogId"));

                    b.Property<int>("DamageDelta")
                        .HasColumnType("integer");

                    b.Property<long>("ExecutionTick")
                        .HasColumnType("bigint");

                    b.Property<long>("MatchId")
                        .HasColumnType("bigint");

                    b.HasKey("LogId");

                    b.ToTable("GuildWarCombatHistory");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.GuildWarDefensiveSnapshot", b =>
                {
                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("GuildId"));

                    b.Property<string>("RosterPayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("GuildId");

                    b.ToTable("GuildWarDefensiveSnapshots");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.GuildWarMatch", b =>
                {
                    b.Property<long>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MatchId"));

                    b.Property<int>("CombatVanguardWP_A")
                        .HasColumnType("integer");

                    b.Property<int>("CombatVanguardWP_B")
                        .HasColumnType("integer");

                    b.Property<int>("GatheringSupplyChainWP_A")
                        .HasColumnType("integer");

                    b.Property<int>("GatheringSupplyChainWP_B")
                        .HasColumnType("integer");

                    b.Property<long>("GuildA_Id")
                        .HasColumnType("bigint");

                    b.Property<long>("GuildB_Id")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MatchEpoch")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionLogisticsWP_A")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionLogisticsWP_B")
                        .HasColumnType("integer");

                    b.HasKey("MatchId");

                    b.ToTable("GuildWarMatches");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.HistoricalMarketArchive", b =>
                {
                    b.Property<long>("ArchiveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ArchiveId"));

                    b.Property<string>("BaseItemId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("BuyerId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CommodityId")
                        .HasColumnType("bigint");

                    b.Property<long?>("EquipmentInstanceId")
                        .HasColumnType("bigint");

                    b.Property<long>("ExecutionPrice")
                        .HasColumnType("bigint");

                    b.Property<long>("ExecutionTimestampEpoch")
                        .HasColumnType("bigint");

                    b.Property<long>("FeeBurned")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsQuarantined")
                        .HasColumnType("boolean");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<long>("OriginalOrderId")
                        .HasColumnType("bigint");

                    b.Property<int>("QualityTier")
                        .HasColumnType("integer");

                    b.Property<long>("SellerId")
                        .HasColumnType("bigint");

                    b.HasKey("ArchiveId");

                    b.ToTable("historical_market_archives");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.LiveOpsEventRotation", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EventId"));

                    b.Property<long>("EndTimestamp")
                        .HasColumnType("bigint");

                    b.Property<byte>("EventType")
                        .HasColumnType("smallint");

                    b.Property<long>("ModifierBitmask")
                        .HasColumnType("bigint");

                    b.HasKey("EventId");

                    b.ToTable("LiveOpsEventRotations");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.MailboxInstance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AttachedEquipmentId")
                        .HasColumnType("bigint");

                    b.Property<string>("BaseItemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("GoldAttachment")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsClaimed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPending")
                        .HasColumnType("boolean");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("QualityTier")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<long>("ReceivedTimestamp")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("MailboxInstances");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.MarketEquipmentInstance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AffixPayload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("BaseItemId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsAffixLocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLockedInEscrow")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsQuarantined")
                        .HasColumnType("boolean");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("QualityTier")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MarketEquipmentInstances");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.MarketOrderRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BaseItemId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("CommodityId")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedAtEpoch")
                        .HasColumnType("bigint");

                    b.Property<long?>("EquipmentInstanceId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsQuarantined")
                        .HasColumnType("boolean");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<int>("QualityTier")
                        .HasColumnType("integer");

                    b.Property<long>("SellerId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CommodityId");

                    b.HasIndex("EquipmentInstanceId");

                    b.ToTable("MarketOrderRecords");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.MentorshipAcademyAssignment", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId", "CharacterId");

                    b.ToTable("MentorshipAcademyAssignments");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.MentorshipContract", b =>
                {
                    b.Property<long>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ContractId"));

                    b.Property<double>("ExpBonusMultiplier")
                        .HasColumnType("double precision");

                    b.Property<long>("MenteePlayerId")
                        .HasColumnType("bigint");

                    b.Property<long>("MentorPlayerId")
                        .HasColumnType("bigint");

                    b.Property<long>("TimestampEstablished")
                        .HasColumnType("bigint");

                    b.HasKey("ContractId");

                    b.HasIndex("MenteePlayerId")
                        .IsUnique();

                    b.ToTable("MentorshipContracts");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.MonsterCodexEntry", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    b.Property<int>("MonsterId")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<int>("FirstDrawnRarity")
                        .HasColumnType("integer");

                    b.Property<int>("KillCount")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId", "MonsterId");

                    b.HasIndex("PlayerId");

                    b.ToTable("monster_codex_entries");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.PlayerAchievement", b =>
                {
                    b.Property<long>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PlayerId"));

                    b.Property<int>("ClaimedAchievementFlags")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId");

                    b.ToTable("player_achievements");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.PlayerChroniclePass", b =>
                {
                    b.Property<long>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PlayerId"));

                    b.Property<int>("AccumulatedXp")
                        .HasColumnType("integer");

                    b.Property<long>("ClaimedMilestonesBitmask")
                        .HasColumnType("bigint");

                    b.Property<int>("PassLevel")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId");

                    b.HasIndex("PassLevel");

                    b.ToTable("PlayerChroniclePasses");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.PlayerCraftingSlot", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<byte>("SlotIndex")
                        .HasColumnType("smallint");

                    b.Property<int>("ActiveRecipeId")
                        .HasColumnType("integer");

                    b.Property<long>("CompletionEpoch")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsReady")
                        .HasColumnType("boolean");

                    b.HasKey("PlayerId", "SlotIndex");

                    b.ToTable("PlayerCraftingSlots");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.PlayerDeviceRegistration", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("DeviceTokenRaw")
                        .HasMaxLength(64)
                        .HasColumnType("bytea");

                    b.Property<byte>("PlatformFamily")
                        .HasColumnType("smallint");

                    b.Property<long>("TimestampRegistered")
                        .HasColumnType("bigint");

                    b.HasKey("PlayerId", "DeviceTokenRaw");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerDeviceRegistrations");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.PlayerLegacyLedger", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("EraId")
                        .HasColumnType("integer");

                    b.Property<int>("CitizenMultiSlotsUnlocked")
                        .HasColumnType("integer");

                    b.Property<int>("LegacyShardBalance")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId", "EraId");

                    b.HasIndex("EraId");

                    b.ToTable("PlayerLegacyLedgers");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.PlayerLifetimeAchievement", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("AchievementId")
                        .HasColumnType("integer");

                    b.Property<int>("CompletedTier")
                        .HasColumnType("integer");

                    b.Property<long>("CurrentProgress")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsClaimed")
                        .HasColumnType("boolean");

                    b.HasKey("PlayerId", "AchievementId");

                    b.ToTable("player_lifetime_achievements");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.PlayerProductionRegistry", b =>
                {
                    b.Property<long>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PlayerId"));

                    b.Property<int>("AlchemyMasteryLevel")
                        .HasColumnType("integer");

                    b.Property<int>("CookingMasteryLevel")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId");

                    b.HasIndex("PlayerId", "CookingMasteryLevel", "AlchemyMasteryLevel");

                    b.ToTable("PlayerProductionRegistries");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.PlayerRaceMastery", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    b.Property<int>("RaceId")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<long>("CumulativeXp")
                        .HasColumnType("bigint");

                    b.Property<int>("MasteryLevel")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId", "RaceId");

                    b.HasIndex("PlayerId");

                    b.ToTable("player_race_masteries");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.PlayerRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AccumulatedTimeBankSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("ActiveDefensivePotionId")
                        .HasColumnType("integer");

                    b.Property<int>("ActiveOffensivePotionId")
                        .HasColumnType("integer");

                    b.Property<Guid>("AuthenticatorToken")
                        .HasColumnType("uuid");

                    b.Property<int>("AvailableSkillPoints")
                        .HasColumnType("integer");

                    b.Property<double>("BankedChronoSeconds")
                        .HasColumnType("double precision");

                    b.Property<int>("BaseConstitution")
                        .HasColumnType("integer");

                    b.Property<int>("BaseDexterity")
                        .HasColumnType("integer");

                    b.Property<int>("BaseLuck")
                        .HasColumnType("integer");

                    b.Property<int>("BaseStrength")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("integer");

                    b.Property<long>("CurrentXp")
                        .HasColumnType("bigint");

                    b.Property<int>("DefensivePotionDurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text");

                    b.Property<long?>("EquippedArmorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("EquippedWeaponId")
                        .HasColumnType("bigint");

                    b.Property<string>("ExternalProviderId")
                        .HasColumnType("text");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsChronoAccelerating")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsQuarantined")
                        .HasColumnType("boolean");

                    b.Property<long>("LastLoginTimestamp")
                        .HasColumnType("bigint");

                    b.Property<long>("LastLogoutTimestamp")
                        .HasColumnType("bigint");

                    b.Property<long>("LegacyPerks")
                        .HasColumnType("bigint");

                    b.Property<long>("LogicEpochCounter")
                        .HasColumnType("bigint");

                    b.Property<int>("LoginStreakDays")
                        .HasColumnType("integer");

                    b.Property<int>("LogisticsGatheringSpeedBonusPct")
                        .HasColumnType("integer");

                    b.Property<int>("OffensivePotionDurationMs")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerGuid")
                        .HasColumnType("uuid");

                    b.Property<int>("PremiumDiamonds")
                        .HasColumnType("integer");

                    b.Property<int>("ProviderType")
                        .HasColumnType("integer");

                    b.Property<bool>("Quarantine_Active")
                        .HasColumnType("boolean");

                    b.Property<int>("SelectedLineageId")
                        .HasColumnType("integer");

                    b.Property<long>("XpPenaltyExpiresEpoch")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.HasIndex("ProviderType", "ExternalProviderId")
                        .IsUnique();

                    b.ToTable("PlayerRecords");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.PlayerRegionCompletion", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer");

                    b.Property<long>("CompletedAtEpoch")
                        .HasColumnType("bigint");

                    b.HasKey("PlayerId", "RegionId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerRegionCompletions");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.PlayerSegmentationProfile", b =>
                {
                    b.Property<long>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PlayerId"));

                    b.Property<double>("ChurnRiskScore")
                        .HasColumnType("double precision");

                    b.Property<int>("CohortTag")
                        .HasColumnType("integer");

                    b.Property<int>("LifetimeValueCents")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId");

                    b.ToTable("PlayerSegmentationProfiles");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.PlayerSkillUnlock", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.Property<long>("UnlockedAtEpoch")
                        .HasColumnType("bigint");

                    b.HasKey("PlayerId", "SkillId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerSkillUnlocks");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.PlayerWorldBossAttempt", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<long>("BossInstanceId")
                        .HasColumnType("bigint");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<long>("SessionStartEpoch")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalInflictedDamage")
                        .HasColumnType("bigint");

                    b.HasKey("PlayerId", "BossInstanceId");

                    b.ToTable("player_world_boss_attempts");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.PrimaryPurchaseLedger", b =>
                {
                    b.Property<string>("TransactionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<byte>("PurchaseState")
                        .HasColumnType("smallint");

                    b.Property<long>("TimestampProcessed")
                        .HasColumnType("bigint");

                    b.HasKey("TransactionId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PrimaryPurchaseLedgers");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.ProcessedTransaction", b =>
                {
                    b.Property<string>("TransactionId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("PremiumDiamondsGranted")
                        .HasColumnType("integer");

                    b.Property<long>("ProcessedAtEpoch")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("TransactionId");

                    b.HasIndex("PlayerId");

                    b.ToTable("ProcessedTransactions");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.SeasonalEraRecord", b =>
                {
                    b.Property<int>("EraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EraId"));

                    b.Property<long>("EndTimestamp")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("EraId");

                    b.ToTable("SeasonalEraRecords");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.SegmentedStorefrontListing", b =>
                {
                    b.Property<int>("ListingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ListingId"));

                    b.Property<int>("DiamondPackageYield")
                        .HasColumnType("integer");

                    b.Property<int>("PriceInCents")
                        .HasColumnType("integer");

                    b.Property<string>("ProductIdentifier")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("TargetCohort")
                        .HasColumnType("integer");

                    b.HasKey("ListingId");

                    b.HasIndex("TargetCohort")
                        .HasDatabaseName("IX_SegmentedStorefrontListings_TargetCohort");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("TargetCohort"), "btree");

                    b.ToTable("SegmentedStorefrontListings");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.VillageInfrastructure", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("BuildingId")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("integer");

                    b.Property<long>("UpgradeCompletesAtEpoch")
                        .HasColumnType("bigint");

                    b.Property<int>("UpgradeTargetLevel")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId", "BuildingId");

                    b.ToTable("VillageInfrastructures");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.VillageResident", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("integer");

                    b.Property<double>("EfficiencyModifier")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("PlayerId", "SlotIndex");

                    b.ToTable("VillageResidents");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.WorldBossSnapshot", b =>
                {
                    b.Property<long>("BossInstanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("BossInstanceId"));

                    b.Property<long>("CurrentHp")
                        .HasColumnType("bigint");

                    b.Property<long>("EventEndEpoch")
                        .HasColumnType("bigint");

                    b.Property<byte>("EventState")
                        .HasColumnType("smallint");

                    b.Property<long>("LastActiveTimestamp")
                        .HasColumnType("bigint");

                    b.Property<long>("MaxHp")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalDamageContributed")
                        .HasColumnType("bigint");

                    b.HasKey("BossInstanceId");

                    b.ToTable("WorldBossSnapshots");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.CharacterLineageRegistry", b =>
                {
                    b.HasOne("FolkIdle.Server.Models.CharacterRecord", "Character")
                        .WithOne("Lineage")
                        .HasForeignKey("FolkIdle.Server.Models.CharacterLineageRegistry", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.GuildMaterialSinkLedger", b =>
                {
                    b.HasOne("FolkIdle.Server.Models.GuildRecord", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.GuildTradeListing", b =>
                {
                    b.HasOne("FolkIdle.Server.Models.MarketEquipmentInstance", "MarketEquipmentInstance")
                        .WithMany()
                        .HasForeignKey("MarketEquipmentInstanceId");

                    b.HasOne("FolkIdle.Server.Models.MarketOrderRecord", "MarketOrderRecord")
                        .WithMany()
                        .HasForeignKey("MarketOrderRecordId");

                    b.Navigation("MarketEquipmentInstance");

                    b.Navigation("MarketOrderRecord");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.MarketOrderRecord", b =>
                {
                    b.HasOne("FolkIdle.Server.Models.CommodityRecord", "Commodity")
                        .WithMany()
                        .HasForeignKey("CommodityId");

                    b.HasOne("FolkIdle.Server.Models.MarketEquipmentInstance", "EquipmentInstance")
                        .WithMany()
                        .HasForeignKey("EquipmentInstanceId");

                    b.Navigation("Commodity");

                    b.Navigation("EquipmentInstance");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.PlayerLegacyLedger", b =>
                {
                    b.HasOne("FolkIdle.Server.Models.SeasonalEraRecord", "Era")
                        .WithMany()
                        .HasForeignKey("EraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Era");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.CharacterRecord", b =>
                {
                    b.Navigation("Lineage");
                });
#pragma warning restore 612, 618
        }
    }
}
