// <auto-generated />
using System;
using FolkIdle.Server.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FolkIdle.Server.Migrations
{
    [DbContext(typeof(FolkIdleDbContext))]
    [Migration("20260707220126_Sprint33_GuildDepot")]
    partial class Sprint33_GuildDepot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FolkIdle.Server.Models.BankEquipmentInstance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AffixPayload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("BaseItemId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsAffixLocked")
                        .HasColumnType("boolean");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("QualityTier")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("BankEquipmentInstances");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.CharacterLineageRegistry", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<int>("GenerationIndex")
                        .HasColumnType("integer");

                    b.Property<long>("GeneticVector")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("ParentMaternalId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentPaternalId")
                        .HasColumnType("uuid");

                    b.HasKey("CharacterId");

                    b.ToTable("character_lineage_registry");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.CharacterRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AgePhase")
                        .HasColumnType("integer");

                    b.Property<bool>("IsLockedInEscrow")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("characters");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.CommodityRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("CommodityRecords");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.EquipmentInstance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AffixPayload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("BaseItemId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsAffixLocked")
                        .HasColumnType("boolean");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("QualityTier")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("EquipmentInstances");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.GuildDepotBalance", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("ItemDefinitionId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("GuildId", "ItemDefinitionId");

                    b.ToTable("GuildDepotBalances");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.GuildMaterialSinkLedger", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CommodityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalAmountContributed")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("GuildMaterialSinkLedgers");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.GuildRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CurrentTier")
                        .HasColumnType("integer");

                    b.Property<int>("MiningMonolithLevel")
                        .HasColumnType("integer");

                    b.Property<int>("MiningMonolithProgress")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("TotalGoldContributed")
                        .HasColumnType("bigint");

                    b.Property<int>("WoodcuttingMonolithLevel")
                        .HasColumnType("integer");

                    b.Property<int>("WoodcuttingMonolithProgress")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("GuildRecords");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.MailboxInstance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AttachedEquipmentId")
                        .HasColumnType("bigint");

                    b.Property<string>("BaseItemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("GoldAttachment")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsClaimed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPending")
                        .HasColumnType("boolean");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("QualityTier")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MailboxInstances");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.MarketEquipmentInstance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AffixPayload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("BaseItemId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsAffixLocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLockedInEscrow")
                        .HasColumnType("boolean");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("QualityTier")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MarketEquipmentInstances");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.MarketOrderRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BaseItemId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("CommodityId")
                        .HasColumnType("bigint");

                    b.Property<long?>("EquipmentInstanceId")
                        .HasColumnType("bigint");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<int>("QualityTier")
                        .HasColumnType("integer");

                    b.Property<long>("SellerId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CommodityId");

                    b.HasIndex("EquipmentInstanceId");

                    b.ToTable("MarketOrderRecords");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.PlayerRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AccumulatedTimeBankSeconds")
                        .HasColumnType("integer");

                    b.Property<Guid>("AuthenticatorToken")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("integer");

                    b.Property<long>("CurrentXp")
                        .HasColumnType("bigint");

                    b.Property<long>("LastLogoutTimestamp")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PlayerGuid")
                        .HasColumnType("uuid");

                    b.Property<int>("SelectedLineageId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PlayerRecords");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.CharacterLineageRegistry", b =>
                {
                    b.HasOne("FolkIdle.Server.Models.CharacterRecord", "Character")
                        .WithOne("Lineage")
                        .HasForeignKey("FolkIdle.Server.Models.CharacterLineageRegistry", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.GuildMaterialSinkLedger", b =>
                {
                    b.HasOne("FolkIdle.Server.Models.GuildRecord", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.MarketOrderRecord", b =>
                {
                    b.HasOne("FolkIdle.Server.Models.CommodityRecord", "Commodity")
                        .WithMany()
                        .HasForeignKey("CommodityId");

                    b.HasOne("FolkIdle.Server.Models.MarketEquipmentInstance", "EquipmentInstance")
                        .WithMany()
                        .HasForeignKey("EquipmentInstanceId");

                    b.Navigation("Commodity");

                    b.Navigation("EquipmentInstance");
                });

            modelBuilder.Entity("FolkIdle.Server.Models.CharacterRecord", b =>
                {
                    b.Navigation("Lineage");
                });
#pragma warning restore 612, 618
        }
    }
}
