// GENERATED by scripts/generate-sprites.mjs - do not edit.
//
// Sprite paths are relative to the server's /sprites route. The server owns
// the files (linked out of client/Assets/Images/Sprites by its csproj), so
// there is exactly one copy of the art and the two clients cannot drift.
//
// Anything absent here has NO artwork, which is a fact about the project
// rather than a bug - callers fall back to a readable placeholder.

export const MONSTER_ICONS: Readonly<Record<number, string>> = {
  "91": "Locations/01/Monsters/Field Mouse.webp",
  "92": "Locations/01/Monsters/Horned Rabbit.webp",
  "93": "Locations/01/Monsters/Meadow Viper.webp",
  "94": "Locations/01/Monsters/Wild Boar.webp",
  "95": "Locations/01/Monsters/Alpha Wolf.webp",
  "96": "Locations/02/Monsters/Thorny Vine.webp",
  "97": "Locations/02/Monsters/Gray Direwolf.webp",
  "98": "Locations/02/Monsters/Forest Dryad.webp",
  "99": "Locations/02/Monsters/Mountain Bear.webp",
  "100": "Locations/02/Monsters/Shadow Lynx.webp",
  "101": "Locations/03/Monsters/Desert Crab.webp",
  "102": "Locations/03/Monsters/Ashen Basilisk.webp",
  "103": "Locations/03/Monsters/Ember Elemental.webp",
  "104": "Locations/03/Monsters/Sandstone Golem.webp",
  "105": "Locations/03/Monsters/Magma Wyrm.webp",
  "106": "Locations/04/Monsters/Ice Bat.webp",
  "107": "Locations/04/Monsters/Snowy Yeti.webp",
  "108": "Locations/04/Monsters/Glacial Wraith.webp",
  "109": "Locations/04/Monsters/Rock Giant.webp",
  "110": "Locations/04/Monsters/Frost Titan.webp",
  "111": "Locations/05/Monsters/Grave Ghoul.webp",
  "112": "Locations/05/Monsters/Fortress Gargoyle.webp",
  "113": "Locations/05/Monsters/Dark Necromancer.webp",
  "114": "Locations/05/Monsters/Death Knight.webp",
  "115": "Locations/05/Monsters/Malakor.webp"
};

export const ITEM_ICONS: Readonly<Record<string, string>> = {
  "birch_log": "Locations/01/Materials&rest/Birch Log.webp",
  "birch_trees_woodcutting_material": "Locations/01/Materials&rest/Birch Tree.webp",
  "birch_twig": "Locations/01/Materials&rest/Birch Twig.webp",
  "copper_ore_crafting_material": "Locations/01/Materials&rest/Copper.webp",
  "golden_birch_log": "Locations/01/Materials&rest/Golden Birch Log.webp",
  "golden_birch_twig": "Locations/01/Materials&rest/Golden Birch Twig.webp",
  "malachite_ore": "Locations/01/Materials&rest/Malachite.webp",
  "roasted_perch_food_consumable": "Locations/01/Materials&rest/Roasted Perch.webp",
  "shimmering_trout": "Locations/01/Materials&rest/Shimmering Trout.webp",
  "sunlit_perch": "Locations/01/Materials&rest/Sunlit Perch.webp",
  "mat_viper_venom": "Locations/01/Materials&rest/Viper Venom Elixir.webp",
  "ancient_eel": "Locations/02/Materials&rest/Ancient Eel.webp",
  "whispering_willow_log": "Locations/02/Materials&rest/Golden Willow log.webp",
  "whispering_willow_twig": "Locations/02/Materials&rest/Golden Willow twig.webp",
  "hematite_ore": "Locations/02/Materials&rest/Hematite.webp",
  "iron_bar_crafting_material": "Locations/02/Materials&rest/Iron bar.webp",
  "moss_bass": "Locations/02/Materials&rest/Moss Bass.webp",
  "viper_stew_food_consumable": "Locations/02/Materials&rest/Viper Stew.webp",
  "willow_log": "Locations/02/Materials&rest/Willow log.webp",
  "willow_logs_woodcutting_material": "Locations/02/Materials&rest/Willow tree.webp",
  "willow_twig": "Locations/02/Materials&rest/Willow twig.webp",
  "obsidian_ore_crafting_material": "Locations/03/Materials&rest/Absidian.webp",
  "acacia_log": "Locations/03/Materials&rest/Acatia log.webp",
  "acacia_twig": "Locations/03/Materials&rest/Acatia twig.webp",
  "bear_stew_food_consumable": "Locations/03/Materials&rest/Bear stew.webp",
  "ironwood_log": "Locations/03/Materials&rest/Golden Acatia log.webp",
  "ironwood_twig": "Locations/03/Materials&rest/Golden Acatia twig.webp",
  "hellfire_salmon": "Locations/03/Materials&rest/Hellfire Salmon.webp",
  "lava_carp": "Locations/03/Materials&rest/Lava Carp.webp",
  "sulfur_ore": "Locations/03/Materials&rest/volcanic sulfur.webp",
  "frost_cod": "Locations/04/Materials&rest/Frost Cod.webp",
  "frostpine_log": "Locations/04/Materials&rest/Frostpine log.webp",
  "frostpine_twig": "Locations/04/Materials&rest/Frostpine twig.webp",
  "glacier_halibut": "Locations/04/Materials&rest/Glacier Halibut.webp",
  "glacier_pine_log": "Locations/04/Materials&rest/Golden Frostpine log.webp",
  "glacier_pine_twig": "Locations/04/Materials&rest/Golden Frostpine twig.webp",
  "silver_bar_crafting_material": "Locations/04/Materials&rest/Silver bar.webp",
  "yeti_platter_food_consumable": "Locations/04/Materials&rest/yeti meat platter.webp",
  "astralite_ore": "Locations/05/Materials&rest/Astralite crystals.webp",
  "ebon_log": "Locations/05/Materials&rest/Ebon log.webp",
  "ebon_twig": "Locations/05/Materials&rest/Ebon twig.webp",
  "death_ward_elixir_defensive_potion_consumable": "Locations/05/Materials&rest/Emergency Revive.webp",
  "void_bark_log": "Locations/05/Materials&rest/Golden Ebon log.webp",
  "void_bark_twig": "Locations/05/Materials&rest/Golden Ebon twig.webp",
  "spectral_lanternfish": "Locations/05/Materials&rest/Spectral Lanternfish.webp",
  "void_ray": "Locations/05/Materials&rest/Void Ray.webp",
  "eq_abyssal_dark_scepter_magic_weapon_slot_base": "Tools&Equipment/Magic Weapons/abyssal dark scepter.webp",
  "eq_birch_wand_magic_weapon_slot_base": "Tools&Equipment/Magic Weapons/birch wand.webp",
  "eq_frost_crystal_staff_magic_weapon_slot_base": "Tools&Equipment/Magic Weapons/frost staff.webp",
  "eq_magus_scepter_magic_weapon_slot_base": "Tools&Equipment/Magic Weapons/magus scepter.webp",
  "eq_moss_staff_magic_weapon_slot_base": "Tools&Equipment/Magic Weapons/moss staff.webp",
  "eq_brawler_axe_melee_weapon_slot_base": "Tools&Equipment/Melee weapons/brawler battleaxe.webp",
  "eq_steel_claymore_melee_weapon_slot_base": "Tools&Equipment/Melee weapons/broadsword claymore.webp",
  "eq_doom_edge_melee_weapon_slot_base": "Tools&Equipment/Melee weapons/Doom Edge.webp",
  "eq_hunter_dagger_melee_weapon_slot_base": "Tools&Equipment/Melee weapons/hunter dagger.webp",
  "eq_obsidian_cleaver_melee_weapon_slot_base": "Tools&Equipment/Melee weapons/obsidian cleaver.webp",
  "eq_ash_shortbow_range_weapon_slot_base": "Tools&Equipment/Ranged Weapons/ashwood shortbow.webp",
  "eq_glacial_crossbow_range_weapon_slot_base": "Tools&Equipment/Ranged Weapons/glacial crossbow.webp",
  "eq_composite_recurve_range_weapon_slot_base": "Tools&Equipment/Ranged Weapons/recurve bow.webp",
  "eq_void_shadow_bow_range_weapon_slot_base": "Tools&Equipment/Ranged Weapons/Void Shadow longbow.webp",
  "eq_willow_longbow_range_weapon_slot_base": "Tools&Equipment/Ranged Weapons/willow longbow.webp",
  "eq_copper_band_ring_1/2_slot_base": "Tools&Equipment/TIER 1 Chiming Steel Set & Linen Bound Set/copper_band.webp",
  "eq_linen_sandals_boots_armor_slot_base": "Tools&Equipment/TIER 1 Chiming Steel Set & Linen Bound Set/linen_boots.webp",
  "eq_linen_hood_helmet_armor_slot_base": "Tools&Equipment/TIER 1 Chiming Steel Set & Linen Bound Set/linen_hood.webp",
  "eq_linen_pendant_amulet_slot_base": "Tools&Equipment/TIER 1 Chiming Steel Set & Linen Bound Set/linen_pendant.webp",
  "eq_linen_shroud_chest_armor_slot_base": "Tools&Equipment/TIER 1 Chiming Steel Set & Linen Bound Set/linen_shroud.webp",
  "eq_linen_trousers_leggings_armor_slot_base": "Tools&Equipment/TIER 1 Chiming Steel Set & Linen Bound Set/linen_trousers.webp",
  "eq_linen_mitts_gloves_armor_slot_base": "Tools&Equipment/TIER 1 Chiming Steel Set & Linen Bound Set/linen_wraps.webp",
  "eq_steel_harness_chest_armor_slot_base": "Tools&Equipment/TIER 1 Chiming Steel Set & Linen Bound Set/steel_cuirass.webp",
  "eq_steel_gauntlets_gloves_armor_slot_base": "Tools&Equipment/TIER 1 Chiming Steel Set & Linen Bound Set/steel_gauntlets.webp",
  "eq_steel_greaves_leggings_armor_slot_base": "Tools&Equipment/TIER 1 Chiming Steel Set & Linen Bound Set/steel_greaves.webp",
  "eq_steel_helm_helmet_armor_slot_base": "Tools&Equipment/TIER 1 Chiming Steel Set & Linen Bound Set/steel_helm.webp",
  "eq_steel_sabatons_boots_armor_slot_base": "Tools&Equipment/TIER 1 Chiming Steel Set & Linen Bound Set/steel_sabatons.webp",
  "eq_hunter_amulet_amulet_slot_base": "Tools&Equipment/TIER 2 Shadow Hunter & Grizzled Sentry Set/hunter_amulet.webp",
  "eq_hunter_bracers_gloves_armor_slot_base": "Tools&Equipment/TIER 2 Shadow Hunter & Grizzled Sentry Set/hunter_bracers.webp",
  "eq_hunter_breeches_leggings_armor_slot_base": "Tools&Equipment/TIER 2 Shadow Hunter & Grizzled Sentry Set/hunter_breeches.webp",
  "eq_hunter_cowl_helmet_armor_slot_base": "Tools&Equipment/TIER 2 Shadow Hunter & Grizzled Sentry Set/hunter_cowl.webp",
  "eq_hunter_boots_boots_armor_slot_base": "Tools&Equipment/TIER 2 Shadow Hunter & Grizzled Sentry Set/hunter_treads.webp",
  "eq_hunter_garb_chest_armor_slot_base": "Tools&Equipment/TIER 2 Shadow Hunter & Grizzled Sentry Set/hunter_vest.webp",
  "eq_iron_signet_ring_1/2_slot_base": "Tools&Equipment/TIER 2 Shadow Hunter & Grizzled Sentry Set/iron_signet.webp",
  "eq_sentry_sabatons_boots_armor_slot_base": "Tools&Equipment/TIER 2 Shadow Hunter & Grizzled Sentry Set/sentry_boots.webp",
  "eq_sentry_gauntlets_gloves_armor_slot_base": "Tools&Equipment/TIER 2 Shadow Hunter & Grizzled Sentry Set/sentry_gloves.webp",
  "eq_sentry_cuirass_chest_armor_slot_base": "Tools&Equipment/TIER 2 Shadow Hunter & Grizzled Sentry Set/sentry_hauberk.webp",
  "eq_sentry_helm_helmet_armor_slot_base": "Tools&Equipment/TIER 2 Shadow Hunter & Grizzled Sentry Set/sentry_helm.webp",
  "eq_sentry_leggings_leggings_armor_slot_base": "Tools&Equipment/TIER 2 Shadow Hunter & Grizzled Sentry Set/sentry_leggings.webp",
  "eq_magus_circlet_helmet_armor_slot_base": "Tools&Equipment/TIER 3 Searing Magus & Obsidian Bastion Set/magus_circlet.webp",
  "eq_magus_vestments_chest_armor_slot_base": "Tools&Equipment/TIER 3 Searing Magus & Obsidian Bastion Set/magus_robe.webp",
  "eq_magus_slippers_boots_armor_slot_base": "Tools&Equipment/TIER 3 Searing Magus & Obsidian Bastion Set/magus_slippers.webp",
  "eq_magus_trousers_leggings_armor_slot_base": "Tools&Equipment/TIER 3 Searing Magus & Obsidian Bastion Set/magus_trousers.webp",
  "eq_magus_wraps_gloves_armor_slot_base": "Tools&Equipment/TIER 3 Searing Magus & Obsidian Bastion Set/magus_wraps.webp",
  "eq_obsidian_gloves_gloves_armor_slot_base": "Tools&Equipment/TIER 3 Searing Magus & Obsidian Bastion Set/obsidian_claws.webp",
  "eq_obsidian_helm_helmet_armor_slot_base": "Tools&Equipment/TIER 3 Searing Magus & Obsidian Bastion Set/obsidian_greathelm.webp",
  "eq_obsidian_greaves_leggings_armor_slot_base": "Tools&Equipment/TIER 3 Searing Magus & Obsidian Bastion Set/obsidian_greaves.webp",
  "eq_obsidian_loop_ring_1/2_slot_base": "Tools&Equipment/TIER 3 Searing Magus & Obsidian Bastion Set/obsidian_loop.webp",
  "eq_obsidian_plate_chest_armor_slot_base": "Tools&Equipment/TIER 3 Searing Magus & Obsidian Bastion Set/obsidian_plate.webp",
  "eq_obsidian_boots_boots_armor_slot_base": "Tools&Equipment/TIER 3 Searing Magus & Obsidian Bastion Set/obsidian_stompers.webp",
  "eq_runic_talisman_amulet_slot_base": "Tools&Equipment/TIER 3 Searing Magus & Obsidian Bastion Set/runic_talisman.webp",
  "eq_brawler_grips_gloves_armor_slot_base": "Tools&Equipment/TIER 4 Frost Brawler & Glacial Monolith Set/brawler_grips.webp",
  "eq_brawler_coat_chest_armor_slot_base": "Tools&Equipment/TIER 4 Frost Brawler & Glacial Monolith Set/brawler_pelt.webp",
  "eq_brawler_pants_leggings_armor_slot_base": "Tools&Equipment/TIER 4 Frost Brawler & Glacial Monolith Set/brawler_pants.webp",
  "eq_brawler_shoes_boots_armor_slot_base": "Tools&Equipment/TIER 4 Frost Brawler & Glacial Monolith Set/brawler_striders.webp",
  "eq_frost_band_ring_1/2_slot_base": "Tools&Equipment/TIER 4 Frost Brawler & Glacial Monolith Set/frost_band.webp",
  "eq_glacial_pendant_amulet_slot_base": "Tools&Equipment/TIER 4 Frost Brawler & Glacial Monolith Set/glacial_pendant.webp",
  "eq_monolith_body_chest_armor_slot_base": "Tools&Equipment/TIER 4 Frost Brawler & Glacial Monolith Set/monolith_carapace.webp",
  "eq_monolith_bracers_gloves_armor_slot_base": "Tools&Equipment/TIER 4 Frost Brawler & Glacial Monolith Set/monolith_fists.webp",
  "eq_monolith_footguards_boots_armor_slot_base": "Tools&Equipment/TIER 4 Frost Brawler & Glacial Monolith Set/monolith_glacier_treads.webp",
  "eq_monolith_guards_leggings_armor_slot_base": "Tools&Equipment/TIER 4 Frost Brawler & Glacial Monolith Set/monolith_guards.webp",
  "eq_monolith_crown_helmet_armor_slot_base": "Tools&Equipment/TIER 4 Frost Brawler & Glacial Monolith Set/monolith_visor.webp",
  "eq_doom_chausses_leggings_armor_slot_base": "Tools&Equipment/TIER 5 Doom Herald & Eternal Dreadnought Set/doom_chausses.webp",
  "eq_doom_claws_gloves_armor_slot_base": "Tools&Equipment/TIER 5 Doom Herald & Eternal Dreadnought Set/doom_claws.webp",
  "eq_doom_crown_helmet_armor_slot_base": "Tools&Equipment/TIER 5 Doom Herald & Eternal Dreadnought Set/doom_crown.webp",
  "eq_doom_pauldrons_chest_armor_slot_base": "Tools&Equipment/TIER 5 Doom Herald & Eternal Dreadnought Set/doom_cuirass.webp",
  "eq_doom_gorget_amulet_slot_base": "Tools&Equipment/TIER 5 Doom Herald & Eternal Dreadnought Set/doom_gorget.webp",
  "eq_doom_sabatons_boots_armor_slot_base": "Tools&Equipment/TIER 5 Doom Herald & Eternal Dreadnought Set/doom_walkers.webp",
  "eq_dread_carapace_chest_armor_slot_base": "Tools&Equipment/TIER 5 Doom Herald & Eternal Dreadnought Set/dread_bulwark_chest.webp",
  "eq_dread_gauntlets_gloves_armor_slot_base": "Tools&Equipment/TIER 5 Doom Herald & Eternal Dreadnought Set/dread_gauntlets.webp",
  "eq_dreadnought_helm_helmet_armor_slot_base": "Tools&Equipment/TIER 5 Doom Herald & Eternal Dreadnought Set/dread_helm.webp",
  "eq_dread_footplates_boots_armor_slot_base": "Tools&Equipment/TIER 5 Doom Herald & Eternal Dreadnought Set/dread_sabatons.webp",
  "eq_dread_signet_ring_1/2_slot_base": "Tools&Equipment/TIER 5 Doom Herald & Eternal Dreadnought Set/dread_signet.webp",
  "eq_dread_tassets_leggings_armor_slot_base": "Tools&Equipment/TIER 5 Doom Herald & Eternal Dreadnought Set/dread_tassets.webp"
};

export const RACE_ICONS: Readonly<Record<number, { male?: string; female?: string }>> = {
  "1": {
    "female": "Characters/Human_Female.webp",
    "male": "Characters/Human_Male.webp"
  },
  "2": {
    "female": "Characters/Vila_Female.webp",
    "male": "Characters/Vila_Male.webp"
  },
  "3": {
    "female": "Characters/Draugr_Female.webp",
    "male": "Characters/Draugr_Male.webp"
  },
  "4": {
    "female": "Characters/Leshy_Female.webp",
    "male": "Characters/Leshy_Male.webp"
  },
  "5": {
    "female": "Characters/Vodnik_Female.webp",
    "male": "Characters/Vodnik_Male.webp"
  },
  "6": {
    "female": "Characters/Bes_Female.webp",
    "male": "Characters/Bes_Male.webp"
  }
};

/** Indexed by tool tier; a tier past the end clamps to the last entry. */
export const TOOL_ICONS: Readonly<Record<'axe' | 'pickaxe' | 'rod', readonly string[]>> = {
  "axe": [
    "Tools&Equipment/axes/Normal axe.webp",
    "Tools&Equipment/axes/Birch axe.webp",
    "Tools&Equipment/axes/Golden Birch axe.webp",
    "Tools&Equipment/axes/Willow axe.webp",
    "Tools&Equipment/axes/Whisper Willow axe.webp",
    "Tools&Equipment/axes/Acatia axe.webp",
    "Tools&Equipment/axes/Ironwood axe.webp",
    "Tools&Equipment/axes/Frostpine axe.webp",
    "Tools&Equipment/axes/Glacier pine axe.webp",
    "Tools&Equipment/axes/Ebon axe.webp",
    "Tools&Equipment/axes/Voidbark axe.webp"
  ],
  "pickaxe": [
    "Tools&Equipment/pickaxes/Normal pickaxe.webp",
    "Tools&Equipment/pickaxes/Birch pickaxe.webp",
    "Tools&Equipment/pickaxes/Golden Birch pickaxe.webp",
    "Tools&Equipment/pickaxes/Willow pickaxe.webp",
    "Tools&Equipment/pickaxes/Whisper Willow pickaxe.webp",
    "Tools&Equipment/pickaxes/Acatia pickaxe.webp",
    "Tools&Equipment/pickaxes/Ironwood pickaxe.webp",
    "Tools&Equipment/pickaxes/Frostpine pickaxe.webp",
    "Tools&Equipment/pickaxes/Glacier pine pickaxe.webp",
    "Tools&Equipment/pickaxes/Ebon pickaxe.webp",
    "Tools&Equipment/pickaxes/Voidbark pickaxe.webp"
  ],
  "rod": [
    "Tools&Equipment/fishing rods/Normal fishing rod.webp",
    "Tools&Equipment/fishing rods/Birch fishing rod.webp",
    "Tools&Equipment/fishing rods/Golden Birch fishing rod.webp",
    "Tools&Equipment/fishing rods/Willow fishing rod.webp",
    "Tools&Equipment/fishing rods/Whisper Willow fishing rod.webp",
    "Tools&Equipment/fishing rods/Acatia fishing rod.webp",
    "Tools&Equipment/fishing rods/Ironwood fishing rod.webp",
    "Tools&Equipment/fishing rods/Frostpine fishing rod.webp",
    "Tools&Equipment/fishing rods/Glacier pine fishing rod.webp",
    "Tools&Equipment/fishing rods/Ebon fishing rod.webp",
    "Tools&Equipment/fishing rods/Voidbark fishing rod.webp"
  ]
};

export const CURRENCY_ICONS: Readonly<{ gold?: string; diamond?: string }> = {
  "diamond": "Others/Gem.webp",
  "gold": "Others/Gold.webp"
};
