// GENERATED by scripts/generate-sprites.mjs - do not edit.
//
// Sprite paths are relative to the server's /sprites route. The server owns
// the files (linked out of client/Assets/Images/Sprites by its csproj), so
// there is exactly one copy of the art and the two clients cannot drift.
//
// Anything absent here has NO artwork, which is a fact about the project
// rather than a bug - callers fall back to a readable placeholder.

export const MONSTER_ICONS: Readonly<Record<number, string>> = {
  "91": "Locations/01/Monsters/Field Mouse.png",
  "92": "Locations/01/Monsters/Horned Rabbit.png",
  "93": "Locations/01/Monsters/Meadow Viper.png",
  "94": "Locations/01/Monsters/Wild Boar.png",
  "95": "Locations/01/Monsters/Alpha Wolf.png",
  "96": "Locations/02/Monsters/Thorny Vine.png",
  "97": "Locations/02/Monsters/Gray Direwolf.png",
  "98": "Locations/02/Monsters/Forest Dryad.png",
  "99": "Locations/02/Monsters/Mountain Bear.png",
  "100": "Locations/02/Monsters/Shadow Lynx.png",
  "101": "Locations/03/Monsters/Desert Crab.png",
  "102": "Locations/03/Monsters/Ashen Basilisk.png",
  "103": "Locations/03/Monsters/Ember Elemental.png",
  "104": "Locations/03/Monsters/Sandstone Golem.png",
  "105": "Locations/03/Monsters/Magma Wyrm.png",
  "106": "Locations/04/Monsters/Ice Bat.png",
  "107": "Locations/04/Monsters/Snowy Yeti.png",
  "108": "Locations/04/Monsters/Glacial Wraith.png",
  "109": "Locations/04/Monsters/Rock Giant.png",
  "110": "Locations/04/Monsters/Frost Titan.png",
  "111": "Locations/05/Monsters/Grave Ghoul.png",
  "112": "Locations/05/Monsters/Fortress Gargoyle.png",
  "113": "Locations/05/Monsters/Dark Necromancer.png",
  "114": "Locations/05/Monsters/Death Knight.png",
  "115": "Locations/05/Monsters/Malakor.png"
};

export const ITEM_ICONS: Readonly<Record<string, string>> = {
  "birch_log": "Locations/01/Materials&rest/Birch Log.png",
  "birch_trees_woodcutting_material": "Locations/01/Materials&rest/Birch Tree.png",
  "birch_twig": "Locations/01/Materials&rest/Birch Twig.png",
  "copper_ore_crafting_material": "Locations/01/Materials&rest/Copper.png",
  "golden_birch_log": "Locations/01/Materials&rest/Golden Birch Log.png",
  "golden_birch_twig": "Locations/01/Materials&rest/Golden Birch Twig.png",
  "malachite_ore": "Locations/01/Materials&rest/Malachite.png",
  "roasted_perch_food_consumable": "Locations/01/Materials&rest/Roasted Perch.png",
  "shimmering_trout": "Locations/01/Materials&rest/Shimmering Trout.png",
  "sunlit_perch": "Locations/01/Materials&rest/Sunlit Perch.png",
  "mat_viper_venom": "Locations/01/Materials&rest/Viper Venom Elixir.png",
  "ancient_eel": "Locations/02/Materials&rest/Ancient Eel.png",
  "whispering_willow_log": "Locations/02/Materials&rest/Golden Willow log.png",
  "whispering_willow_twig": "Locations/02/Materials&rest/Golden Willow twig.png",
  "hematite_ore": "Locations/02/Materials&rest/Hematite.png",
  "iron_bar_crafting_material": "Locations/02/Materials&rest/Iron bar.png",
  "moss_bass": "Locations/02/Materials&rest/Moss Bass.png",
  "viper_stew_food_consumable": "Locations/02/Materials&rest/Viper Stew.png",
  "willow_log": "Locations/02/Materials&rest/Willow log.png",
  "willow_logs_woodcutting_material": "Locations/02/Materials&rest/Willow tree.png",
  "willow_twig": "Locations/02/Materials&rest/Willow twig.png",
  "obsidian_ore_crafting_material": "Locations/03/Materials&rest/Absidian.png",
  "acacia_log": "Locations/03/Materials&rest/Acatia log.png",
  "acacia_twig": "Locations/03/Materials&rest/Acatia twig.png",
  "bear_stew_food_consumable": "Locations/03/Materials&rest/Bear stew.png",
  "ironwood_log": "Locations/03/Materials&rest/Golden Acatia log.png",
  "ironwood_twig": "Locations/03/Materials&rest/Golden Acatia twig.png",
  "hellfire_salmon": "Locations/03/Materials&rest/Hellfire Salmon.png",
  "lava_carp": "Locations/03/Materials&rest/Lava Carp.png",
  "sulfur_ore": "Locations/03/Materials&rest/volcanic sulfur.png",
  "frost_cod": "Locations/04/Materials&rest/Frost Cod.png",
  "frostpine_log": "Locations/04/Materials&rest/Frostpine log.png",
  "frostpine_twig": "Locations/04/Materials&rest/Frostpine twig.png",
  "glacier_halibut": "Locations/04/Materials&rest/Glacier Halibut.png",
  "glacier_pine_log": "Locations/04/Materials&rest/Golden Frostpine log.png",
  "glacier_pine_twig": "Locations/04/Materials&rest/Golden Frostpine twig.png",
  "silver_bar_crafting_material": "Locations/04/Materials&rest/Silver bar.png",
  "yeti_platter_food_consumable": "Locations/04/Materials&rest/yeti meat platter.png",
  "astralite_ore": "Locations/05/Materials&rest/Astralite crystals.png",
  "ebon_log": "Locations/05/Materials&rest/Ebon log.png",
  "ebon_twig": "Locations/05/Materials&rest/Ebon twig.png",
  "death_ward_elixir_defensive_potion_consumable": "Locations/05/Materials&rest/Emergency Revive.png",
  "void_bark_log": "Locations/05/Materials&rest/Golden Ebon log.png",
  "void_bark_twig": "Locations/05/Materials&rest/Golden Ebon twig.png",
  "spectral_lanternfish": "Locations/05/Materials&rest/Spectral Lanternfish.png",
  "void_ray": "Locations/05/Materials&rest/Void Ray.png",
  "eq_abyssal_dark_scepter_magic_weapon_slot_base": "Tools&Equipment/Magic Weapons/abyssal dark scepter.png",
  "eq_birch_wand_magic_weapon_slot_base": "Tools&Equipment/Magic Weapons/birch wand.png",
  "eq_frost_crystal_staff_magic_weapon_slot_base": "Tools&Equipment/Magic Weapons/frost staff.png",
  "eq_magus_scepter_magic_weapon_slot_base": "Tools&Equipment/Magic Weapons/magus scepter.png",
  "eq_moss_staff_magic_weapon_slot_base": "Tools&Equipment/Magic Weapons/moss staff.png",
  "eq_brawler_axe_melee_weapon_slot_base": "Tools&Equipment/Melee weapons/brawler battleaxe.png",
  "eq_steel_claymore_melee_weapon_slot_base": "Tools&Equipment/Melee weapons/broadsword claymore.png",
  "eq_doom_edge_melee_weapon_slot_base": "Tools&Equipment/Melee weapons/Doom Edge.png",
  "eq_hunter_dagger_melee_weapon_slot_base": "Tools&Equipment/Melee weapons/hunter dagger.png",
  "eq_obsidian_cleaver_melee_weapon_slot_base": "Tools&Equipment/Melee weapons/obsidian cleaver.png",
  "eq_ash_shortbow_range_weapon_slot_base": "Tools&Equipment/Ranged Weapons/ashwood shortbow.png",
  "eq_glacial_crossbow_range_weapon_slot_base": "Tools&Equipment/Ranged Weapons/glacial crossbow.png",
  "eq_composite_recurve_range_weapon_slot_base": "Tools&Equipment/Ranged Weapons/recurve bow.png",
  "eq_void_shadow_bow_range_weapon_slot_base": "Tools&Equipment/Ranged Weapons/Void Shadow longbow.png",
  "eq_willow_longbow_range_weapon_slot_base": "Tools&Equipment/Ranged Weapons/willow longbow.png",
  "eq_linen_sandals_boots_armor_slot_base": "Tools&Equipment/TIER 1 Chiming Steel Set & Linen Bound Set/linen_boots.png",
  "eq_linen_hood_helmet_armor_slot_base": "Tools&Equipment/TIER 1 Chiming Steel Set & Linen Bound Set/linen_hood.png",
  "eq_linen_shroud_chest_armor_slot_base": "Tools&Equipment/TIER 1 Chiming Steel Set & Linen Bound Set/linen_shroud.png",
  "eq_linen_trousers_leggings_armor_slot_base": "Tools&Equipment/TIER 1 Chiming Steel Set & Linen Bound Set/linen_trousers.png",
  "eq_linen_mitts_gloves_armor_slot_base": "Tools&Equipment/TIER 1 Chiming Steel Set & Linen Bound Set/linen_wraps.png",
  "steel_sallet_helmet_armor_slot_base": "Tools&Equipment/TIER 1 Chiming Steel Set & Linen Bound Set/steel_helm.png",
  "eq_hunter_breeches_leggings_armor_slot_base": "Tools&Equipment/TIER 2 Shadow Hunter & Grizzled Sentry Set/hunter_breeches.png",
  "eq_hunter_boots_boots_armor_slot_base": "Tools&Equipment/TIER 2 Shadow Hunter & Grizzled Sentry Set/hunter_treads.png",
  "eq_hunter_garb_chest_armor_slot_base": "Tools&Equipment/TIER 2 Shadow Hunter & Grizzled Sentry Set/hunter_vest.png",
  "iron_band_ring_1/2_slot_base": "Tools&Equipment/TIER 2 Shadow Hunter & Grizzled Sentry Set/iron_signet.png",
  "eq_sentry_sabatons_boots_armor_slot_base": "Tools&Equipment/TIER 2 Shadow Hunter & Grizzled Sentry Set/sentry_boots.png",
  "eq_sentry_gauntlets_gloves_armor_slot_base": "Tools&Equipment/TIER 2 Shadow Hunter & Grizzled Sentry Set/sentry_gloves.png",
  "eq_sentry_cuirass_chest_armor_slot_base": "Tools&Equipment/TIER 2 Shadow Hunter & Grizzled Sentry Set/sentry_hauberk.png",
  "eq_sentry_helm_helmet_armor_slot_base": "Tools&Equipment/TIER 2 Shadow Hunter & Grizzled Sentry Set/sentry_helm.png",
  "eq_sentry_leggings_leggings_armor_slot_base": "Tools&Equipment/TIER 2 Shadow Hunter & Grizzled Sentry Set/sentry_leggings.png",
  "eq_magus_vestments_chest_armor_slot_base": "Tools&Equipment/TIER 3 Searing Magus & Obsidian Bastion Set/magus_robe.png",
  "eq_magus_slippers_boots_armor_slot_base": "Tools&Equipment/TIER 3 Searing Magus & Obsidian Bastion Set/magus_slippers.png",
  "eq_magus_trousers_leggings_armor_slot_base": "Tools&Equipment/TIER 3 Searing Magus & Obsidian Bastion Set/magus_trousers.png",
  "eq_obsidian_gloves_gloves_armor_slot_base": "Tools&Equipment/TIER 3 Searing Magus & Obsidian Bastion Set/obsidian_claws.png",
  "eq_obsidian_helm_helmet_armor_slot_base": "Tools&Equipment/TIER 3 Searing Magus & Obsidian Bastion Set/obsidian_greathelm.png",
  "eq_obsidian_greaves_leggings_armor_slot_base": "Tools&Equipment/TIER 3 Searing Magus & Obsidian Bastion Set/obsidian_greaves.png",
  "eq_obsidian_plate_chest_armor_slot_base": "Tools&Equipment/TIER 3 Searing Magus & Obsidian Bastion Set/obsidian_plate.png",
  "eq_obsidian_boots_boots_armor_slot_base": "Tools&Equipment/TIER 3 Searing Magus & Obsidian Bastion Set/obsidian_stompers.png",
  "eq_brawler_coat_chest_armor_slot_base": "Tools&Equipment/TIER 4 Frost Brawler & Glacial Monolith Set/brawler_pelt.png",
  "eq_brawler_pants_leggings_armor_slot_base": "Tools&Equipment/TIER 4 Frost Brawler & Glacial Monolith Set/brawler_pants.png",
  "eq_brawler_shoes_boots_armor_slot_base": "Tools&Equipment/TIER 4 Frost Brawler & Glacial Monolith Set/brawler_striders.png",
  "eq_monolith_body_chest_armor_slot_base": "Tools&Equipment/TIER 4 Frost Brawler & Glacial Monolith Set/monolith_carapace.png",
  "eq_monolith_bracers_gloves_armor_slot_base": "Tools&Equipment/TIER 4 Frost Brawler & Glacial Monolith Set/monolith_fists.png",
  "eq_monolith_footguards_boots_armor_slot_base": "Tools&Equipment/TIER 4 Frost Brawler & Glacial Monolith Set/monolith_glacier_treads.png",
  "eq_monolith_guards_leggings_armor_slot_base": "Tools&Equipment/TIER 4 Frost Brawler & Glacial Monolith Set/monolith_guards.png",
  "eq_monolith_crown_helmet_armor_slot_base": "Tools&Equipment/TIER 4 Frost Brawler & Glacial Monolith Set/monolith_visor.png",
  "eq_doom_chausses_leggings_armor_slot_base": "Tools&Equipment/TIER 5 Doom Herald & Eternal Dreadnought Set/doom_chausses.png",
  "eq_doom_pauldrons_chest_armor_slot_base": "Tools&Equipment/TIER 5 Doom Herald & Eternal Dreadnought Set/doom_cuirass.png",
  "eq_doom_sabatons_boots_armor_slot_base": "Tools&Equipment/TIER 5 Doom Herald & Eternal Dreadnought Set/doom_walkers.png",
  "eq_dread_carapace_chest_armor_slot_base": "Tools&Equipment/TIER 5 Doom Herald & Eternal Dreadnought Set/dread_bulwark_chest.png",
  "eq_dread_gauntlets_gloves_armor_slot_base": "Tools&Equipment/TIER 5 Doom Herald & Eternal Dreadnought Set/dread_gauntlets.png",
  "eq_dread_footplates_boots_armor_slot_base": "Tools&Equipment/TIER 5 Doom Herald & Eternal Dreadnought Set/dread_sabatons.png",
  "eq_dread_tassets_leggings_armor_slot_base": "Tools&Equipment/TIER 5 Doom Herald & Eternal Dreadnought Set/dread_tassets.png"
};

export const RACE_ICONS: Readonly<Record<number, { male?: string; female?: string }>> = {
  "1": {
    "female": "Characters/Human_Female.png",
    "male": "Characters/Human_Male.png"
  },
  "2": {
    "female": "Characters/Vila_Female.png",
    "male": "Characters/Vila_Male.png"
  },
  "3": {
    "female": "Characters/Draugr_Female.png",
    "male": "Characters/Draugr_Male.png"
  },
  "4": {
    "female": "Characters/Bes_Female.png",
    "male": "Characters/Bes_Male.png"
  },
  "5": {
    "female": "Characters/Vodnik_Female.png",
    "male": "Characters/Vodnik_Male.png"
  },
  "6": {
    "female": "Characters/Leshy_Female.png",
    "male": "Characters/Leshy_Male.png"
  }
};

/** Indexed by tool tier; a tier past the end clamps to the last entry. */
export const TOOL_ICONS: Readonly<Record<'axe' | 'pickaxe' | 'rod', readonly string[]>> = {
  "axe": [
    "Tools&Equipment/axes/Normal axe.png",
    "Tools&Equipment/axes/Birch axe.png",
    "Tools&Equipment/axes/Golden Birch axe.png",
    "Tools&Equipment/axes/Willow axe.png",
    "Tools&Equipment/axes/Whisper Willow axe.png",
    "Tools&Equipment/axes/Acatia axe.png",
    "Tools&Equipment/axes/Ironwood axe.png",
    "Tools&Equipment/axes/Frostpine axe.png",
    "Tools&Equipment/axes/Glacier pine axe.png",
    "Tools&Equipment/axes/Ebon axe.png",
    "Tools&Equipment/axes/Voidbark axe.png"
  ],
  "pickaxe": [
    "Tools&Equipment/pickaxes/Normal pickaxe.png",
    "Tools&Equipment/pickaxes/Birch pickaxe.png",
    "Tools&Equipment/pickaxes/Golden Birch pickaxe.png",
    "Tools&Equipment/pickaxes/Willow pickaxe.png",
    "Tools&Equipment/pickaxes/Whisper Willow pickaxe.png",
    "Tools&Equipment/pickaxes/Acatia pickaxe.png",
    "Tools&Equipment/pickaxes/Ironwood pickaxe.png",
    "Tools&Equipment/pickaxes/Frostpine pickaxe.png",
    "Tools&Equipment/pickaxes/Glacier pine pickaxe.png",
    "Tools&Equipment/pickaxes/Ebon pickaxe.png",
    "Tools&Equipment/pickaxes/Voidbark pickaxe.png"
  ],
  "rod": [
    "Tools&Equipment/fishing rods/Normal fishing rod.png",
    "Tools&Equipment/fishing rods/Birch fishing rod.png",
    "Tools&Equipment/fishing rods/Golden Birch fishing rod.png",
    "Tools&Equipment/fishing rods/Willow fishing rod.png",
    "Tools&Equipment/fishing rods/Whisper Willow fishing rod.png",
    "Tools&Equipment/fishing rods/Acatia fishing rod.png",
    "Tools&Equipment/fishing rods/Ironwood fishing rod.png",
    "Tools&Equipment/fishing rods/Frostpine fishing rod.png",
    "Tools&Equipment/fishing rods/Glacier pine fishing rod.png",
    "Tools&Equipment/fishing rods/Ebon fishing rod.png",
    "Tools&Equipment/fishing rods/Voidbark fishing rod.png"
  ]
};

export const CURRENCY_ICONS: Readonly<{ gold?: string; diamond?: string }> = {
  "diamond": "Others/Gem.png",
  "gold": "Others/Gold.png"
};
