// Modul: THE NATIVE PROJECTS ARE COMMITTED, SO THEY CAN ROT IN SILENCE.
//
// android/ and ios/ are generated by `cap sync` and then checked in. Nothing
// in this repository compiles them - CI assembles a debug APK, which covers
// Android, and there is no Apple toolchain anywhere in the project. So the
// iOS half is verified by reading, or not at all.
//
// Both facts below were WRONG in the tree at the same time and neither had a
// symptom anybody could have seen from here:
//
//   1. Package.swift carried Windows path separators, which are escape
//      introducers in a Swift string literal - the manifest does not parse.
//      See scripts/normalize-native.mjs for the full reading of that literal.
//
//   2. @capacitor/app and @capacitor/push-notifications were not installed at
//      all, while three modules read their plugins off `Capacitor.Plugins`.
//      Reading off the global is correct - it keeps them out of the WEB bundle
//      - but the native shell only injects a plugin that `cap sync` LINKED,
//      and it links what package.json declares. So the hardware back button
//      fell through to Capacitor's default (exit the app from any screen, the
//      exact bug backButton.ts was written to fix) and push was inert on every
//      device regardless of Firebase.
//
// The general rule this encodes: A PLUGIN READ OFF THE GLOBAL STILL NEEDS TO
// BE A DEPENDENCY. "Not imported" and "not installed" look identical in the
// web build and are opposites on a phone.
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = (...parts: string[]) => readFileSync(join(root, ...parts), 'utf8');

/**
 * Every Capacitor plugin this client reads off the injected global, and the
 * `Capacitor.Plugins` key it is injected under.
 *
 * Add a row here when you add a `Capacitor.Plugins.X` read. The point is that
 * doing so forces the npm dependency and the native link to be decided at the
 * same moment, rather than three months apart.
 */
const REQUIRED_PLUGINS = [
  { pkg: '@capacitor/app', global: 'App', usedBy: 'lifecycle.ts, backButton.ts' },
  { pkg: '@capacitor/preferences', global: 'Preferences', usedBy: 'auth.ts (documented, sync fallback)' },
  {
    pkg: '@capacitor/push-notifications',
    global: 'PushNotifications',
    usedBy: 'push.ts',
  },
  {
    pkg: '@capgo/capacitor-updater',
    global: 'CapacitorUpdater',
    usedBy: 'liveUpdate.ts',
  },
] as const;

describe('the committed native projects', () => {
  const pkg = JSON.parse(read('package.json')) as {
    dependencies?: Record<string, string>;
    devDependencies?: Record<string, string>;
  };

  for (const { pkg: name, global, usedBy } of REQUIRED_PLUGINS) {
    it(`declares ${name}, whose plugin ${usedBy} reads as Capacitor.Plugins.${global}`, () => {
      expect(pkg.dependencies ?? {}).toHaveProperty(name);
    });

    it(`links ${name} into the Android project`, () => {
      // capacitor.settings.gradle is what `cap sync` writes; a plugin absent
      // from it is one the native shell will never inject.
      // `@capacitor/x` links as `capacitor-x`; `@capgo/x` as `capgo-x`.
      expect(read('android', 'capacitor.settings.gradle')).toContain(
        name.replace('@', '').replace('/', '-'),
      );
    });

    it(`links ${name} into the iOS project`, () => {
      expect(read('ios', 'App', 'CapApp-SPM', 'Package.swift')).toContain(name);
    });
  }

  it('writes Package.swift paths with forward slashes, not Windows separators', () => {
    // A backslash here is not a cosmetic difference: `\.` and `\@` are invalid
    // Swift escapes and `\n` is a newline, so the manifest fails to parse.
    // It also makes CI's `git diff --exit-code -- android ios` permanently
    // dirty, because the Linux runner regenerates forward slashes.
    const manifest = read('ios', 'App', 'CapApp-SPM', 'Package.swift');
    const paths = [...manifest.matchAll(/path:\s*"([^"]*)"/g)].map((m) => m[1]);

    expect(paths.length).toBeGreaterThan(0);
    for (const p of paths) {
      expect(p, `${p} - run: npm run normalize:native`).not.toContain('\\');
    }
  });

  it('keeps gradlew executable in the git index, or Linux cannot run it', () => {
    // Modul: `./gradlew: Permission denied`, exit code 126 - the real reason
    // CI's APK step failed, after three other failures had been stacked in
    // front of it.
    //
    // Windows has no executable bit, so a file added from this machine is
    // committed 100644 and the Linux runner cannot exec it. It has to be 100755
    // in the INDEX; the working-tree mode is meaningless here and checking it
    // would pass on Windows forever.
    //
    // It also survived a careful Docker reproduction of the whole CI job, which
    // is the lesson worth keeping: the repo was copied in over a Windows bind
    // mount, and those present every file as 0777. A reproduction can be
    // faithful in every respect except the one that matters.
    const mode = execFileSync('git', ['ls-files', '-s', '--', 'android/gradlew'], {
      cwd: root,
      encoding: 'utf8',
    })
      .trim()
      .split(/\s+/)[0];

    expect(mode, 'run: git update-index --chmod=+x client_web/android/gradlew').toBe('100755');
  });

  it('declares POST_NOTIFICATIONS, which the push plugin requests but does not declare', () => {
    // The plugin asks for it at runtime via @Permission. Android 13+ refuses a
    // runtime request for a permission the MERGED manifest does not declare,
    // and refuses it silently - no dialog, an immediate "denied". The plugin's
    // own AndroidManifest.xml declares only its MessagingService, so this has
    // to be in the app's.
    expect(read('android', 'app', 'src', 'main', 'AndroidManifest.xml')).toContain(
      'android.permission.POST_NOTIFICATIONS',
    );
  });
});
