name: Acquire Unity License

on:
  workflow_dispatch:

jobs:
  activation:
    name: Request manual license file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Request manual license file
        uses: game-ci/unity-builder@v4
        id: get-alf
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneLinux64
          version: 6000.5.2f1
          customParameters: -batchmode -createManualActivationFile

      - name: Upload ALF file
        uses: actions/upload-artifact@v4
        with:
          name: Unity-Activation-File
          path: '*.alf'
